[2023-06-30T10:43:41.415+0100] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cnt_to_db.insert_into_table manual__2023-06-30T09:43:36.303278+00:00 [queued]>
[2023-06-30T10:43:41.428+0100] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cnt_to_db.insert_into_table manual__2023-06-30T09:43:36.303278+00:00 [queued]>
[2023-06-30T10:43:41.429+0100] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-30T10:43:41.442+0100] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2023-06-30 09:43:36.303278+00:00
[2023-06-30T10:43:41.446+0100] {standard_task_runner.py:57} INFO - Started process 139038 to run task
[2023-06-30T10:43:41.450+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'cnt_to_db', 'insert_into_table', 'manual__2023-06-30T09:43:36.303278+00:00', '--job-id', '22', '--raw', '--subdir', '/home/haboubi/Desktop/api/API_weather/dags/__pycache__/dag_connect_db.py', '--cfg-path', '/tmp/tmp5vnvddf_']
[2023-06-30T10:43:41.452+0100] {standard_task_runner.py:85} INFO - Job 22: Subtask insert_into_table
[2023-06-30T10:43:41.531+0100] {task_command.py:410} INFO - Running <TaskInstance: cnt_to_db.insert_into_table manual__2023-06-30T09:43:36.303278+00:00 [running]> on host haboubi-VivoBook-15-ASUS-Laptop-X540UB
[2023-06-30T10:43:41.647+0100] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='haboubi' AIRFLOW_CTX_DAG_ID='cnt_to_db' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2023-06-30T09:43:36.303278+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-30T09:43:36.303278+00:00'
[2023-06-30T10:43:41.648+0100] {sql.py:265} INFO - Executing: 
                insert into dag_runs_1 (dt, dag_id) values ('2023-06-30','cnt_to_db')
                
                
[2023-06-30T10:43:41.665+0100] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-06-30T10:43:41.697+0100] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-06-30T10:43:41.711+0100] {sql.py:375} INFO - Running statement: 
                insert into dag_runs_1 (dt, dag_id) values ('2023-06-30','cnt_to_db')
                
                , parameters: None
[2023-06-30T10:43:41.712+0100] {sql.py:384} INFO - Rows affected: 1
[2023-06-30T10:43:41.730+0100] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=cnt_to_db, task_id=insert_into_table, execution_date=20230630T094336, start_date=20230630T094341, end_date=20230630T094341
[2023-06-30T10:43:41.783+0100] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-30T10:43:41.808+0100] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
